version: '3.8'

networks:
  my_network:
    driver: bridge
services:
  db:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=jogos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5433:5432"
    networks:
      - my_network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - my_network